# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb8d1c480998465bb974a96a04d0d14d54528229fb2a154fbeeaa83e8a0593704ba1ecf35cdd7619f67d47e46a103f94eac4194ccfa4796561b3a3f4cffa993

test:
  secret_key_base: 8fe1d0b40aa213e0f531fb16797742f312405b9d934adaf274606b6448aa6c79d42591e7e8e61af8fffadcce437f428f421d0753d4b11727b97d7682fc5385a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
